[package]
name = "edg-signal"
version = "0.1.0"
authors = ["zhang-dong-dong <2209940496@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
